### ISSUE TITLE
Error when launching mpwt

### ISSUE THREAD

**Issue by lcottret** [AuReMe/mpwt#84]
Hi,

I have a python error when I launch mpwt.

```
mpwt -v
Traceback (most recent call last):
  File "/home/lcottret/.local/bin/mpwt", line 8, in <module>
    sys.exit(run_mpwt())
  File "/home/lcottret/.local/lib/python3.7/site-packages/mpwt/__main__.py", line 387, in run_mpwt
    permission=permission)
  File "/home/lcottret/.local/lib/python3.7/site-packages/mpwt/mpwt_workflow.py", line 112, in multiprocess_pwt
    if ptools_version >= (26, 0):
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
```

mpwt version : 0.8.1
Installation with pip
Python version : 3.7
ptools version : 26.0
OS : Debian

Ludo

**Comment by lcottret** [comment]
Ok, this is because my ptools has problems, sorry. The result of the process does not contain "Pathway Tools version".
Maybe, the error message could be clearer :-).

**Comment by ArnaudBelcour** [comment]
Hi @lcottret,

Indeed, the error message should be better. I have made a better error message in version 0.8.2.

Thank you for the issue and the feedback.
